name: Probot Example
description: "Example Action built with Probot"
branding:
  icon: "gift"
  color: orange
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
